In [1]:
import numpy as np
import pandas as pd

#1

In [8]:
M1 = np.array([[17, -11],
              [6, -3]])
M1

array([[ 17, -11],
       [  6,  -3]])

In [9]:
np.linalg.det(M1)

14.999999999999993

In [10]:
M2 = np.array([[1, 1, 2],
               [2, 3, 1],
               [3, 4, -5]])
M2

array([[ 1,  1,  2],
       [ 2,  3,  1],
       [ 3,  4, -5]])

In [11]:
np.linalg.det(M2)

-7.999999999999998

#2

In [12]:
A1 = np.array([[-3, -2],
               [3, 3]])
A1

array([[-3, -2],
       [ 3,  3]])

In [14]:
np.linalg.inv(A1)

array([[-1.        , -0.66666667],
       [ 1.        ,  1.        ]])

In [17]:
A2 = np.array([[1, 0, 1],
               [0, 1, 1],
               [1, 1, 1]])
A2

array([[1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [18]:
np.linalg.inv(A2)

array([[ 0., -1.,  1.],
       [-1.,  0.,  1.],
       [ 1.,  1., -1.]])

#3

In [19]:
A = np.array([[1, 4, 3, -1, 5],
              [1, -1, 1, 2, 6],
              [4, 1, 6, 5, 9]])
A

array([[ 1,  4,  3, -1,  5],
       [ 1, -1,  1,  2,  6],
       [ 4,  1,  6,  5,  9]])

In [21]:
import sympy as sm
AM = sm.Matrix(A)

In [22]:
AM.rref()

(Matrix([
 [1, 0, 7/5,  7/5, 0],
 [0, 1, 2/5, -3/5, 0],
 [0, 0,   0,    0, 1]]),
 (0, 1, 4))

In [23]:
B = np.array([[1, -2, 1, -1, 3],
              [2, -4, 1, 1, 2],
              [1, -2, -2, 3, 1]])

In [24]:
BM = sm.Matrix(B)

In [25]:
BM.rref()

(Matrix([
 [1, -2, 0, 0,  3],
 [0,  0, 1, 0, -2],
 [0,  0, 0, 1, -2]]),
 (0, 2, 3))

#Command

In [26]:
arr = np.array([[1, 2, 3],
                [4, 2, 7],
                [8, 1, 6]])
arr

array([[1, 2, 3],
       [4, 2, 7],
       [8, 1, 6]])

In [27]:
arr.shape

(3, 3)

In [30]:
arr[0, :]

array([1, 2, 3])

In [31]:
arr[:, 1]

array([2, 2, 1])

In [32]:
arr[1, 2]

7

In [33]:
arr[0:2, 0:2]

array([[1, 2],
       [4, 2]])

In [34]:
rvec = np.array([1, 2, 3])
rvec

array([1, 2, 3])

In [35]:
cvec = np.array([[1],
                 [2],
                 [3]])
cvec

array([[1],
       [2],
       [3]])