# NumPy Basics
Welcome to the beginner’s guide to NumPy! If you have comments or suggestions, please don’t hesitate to share it in the end of the session!

![alt_text](S1-pics\NumPy_logo.png)

## How to import NumPy
Any time you want to use a package or library in your code, you first need to make it accessible.

In order to start using NumPy and all of the functions available in NumPy, you’ll need to import it. This can be easily done with this import statement:

In [1]:
import numpy as np

(We shorten `numpy` to `np` in order to save time and also to keep code standardized so that anyone working with your code can easily understand and run it.)

## About Arrays


An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array `dtype`.


**For example:**

Create 1-D array with values from 1 to 6

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

This is `1-D array`, values are hard coded.

**While,**


In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

This is `2-D array`, values are also hard coded.

### Acessing Array Elements
We can access the elements in the array using square brackets `[]`.
> Remember that indexing in NumPy starts at `0`.


In [4]:
a[0]

array([1, 2, 3, 4])

## More about Arrays

You might occasionally hear an array referred to as a `ndarray`, which is shorthand for `N-dimensional array`.

An N-dimensional array is simply an array with any number of dimensions, eg: `1-D`, or `one-dimensional` array, `2-D`, or `two-dimensional` array, and so on.

The `NumPy ndarray` class is used to represent both `matrices` and `vectors`.

- A `vector` is an array with a `single dimension` (there’s no difference between row and column vectors),
- while a `matrix` refers to an array with `two dimensions`.
- For `3-D` or `higher dimensional` arrays, the term `tensor` is also commonly used.

> In `NumPy`, dimensions are called `axes`.

This means that if you have a 2D array that looks like this:

In [5]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

Your array has `2` axes.
- The first axis has a length of `2` and
- the second axis has a length of `3`.

> Array **attributes** reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array, you can often access an array through its attributes.
[More about attribuites](https://numpy.org/doc/stable/reference/arrays.ndarray.html#arrays-ndarray).

# Section 1: How to create a basic array
This section covers `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`, `dtype`

To create a NumPy array, you can use the function `np.array()`.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

**You can find more information about data types [here](https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes).**

### Basic Array

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

You can visualize your array this way:
![alt text](S1-pics\a.png)
*Be aware that these visualizations are meant to simplify ideas and give you a basic understanding of NumPy concepts and mechanics. Arrays and array operations are much more complicated than are captured here!*

### Array of Zeros
Besides creating an `array` from a sequence of elements, you can easily create an array filled with `0`’s:

*Hint*
- Use `.zeros()` function.

In [7]:
# Code Here
z = np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Array filled with 1’s
Write array contains `two` elements have `1`'s as values

In [8]:
# Code here
s = np.ones(2)
s

array([1., 1.])

### Empty Array

The function `empty` creates an array whose initial content is `random` and depends on the state of the memory. The reason to use empty over zeros (or something similar) is `speed` - just make sure to fill every element afterwards!

In [9]:
# Create an empty array with 3 elements
# Code here
e = np.empty(3)
e  # may vary

array([1., 1., 1.])

### Array within range

You can create an array with a range of elements:

In [10]:
# create an array with a range of 4
# code here
r = np.arange(4)
r

array([0, 1, 2, 3])

**Note That**
    The array that contains a `range` of evenly spaced `intervals`. To do this, you will specify the `first number`, `last number`, and the `step size`.

In [11]:
# create an array starts with 2, ends with 9 and step size 2.
# code here
i = np.arange(2, 9, 2)
i

array([2, 4, 6, 8])

You can also use `np.linspace()` to create an array with values that are `spaced linearly` in a specified interval:

In [12]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Specifying your data type

While the default data type is floating point (`np.float64`), you can explicitly specify which data type you want using the `dtype` keyword.

In [13]:
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

**Learn more about creating arrays [here](https://numpy.org/doc/stable/user/quickstart.html#quickstart-array-creation).**

# Section 2: Adding, removing, and sorting elements
This section covers `np.sort()`, `np.concatenate()`

### Sorting

Sorting an element is simple with `np.sort()`. You can specify the `axis`, `kind`, and `order` when you call the function.

If you start with this array:

In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

You can quickly sort the numbers in `ascending order` with:

In [15]:
# code here
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to `sort`, which returns a sorted copy of an array, you can use:

- `argsort`, which is an indirect sort along a specified axis,
- `lexsort`, which is an indirect stable sort on multiple keys,
- `searchsorted`, which will find elements in a sorted array, and
- `partition`, which is a partial sort.

To read more about sorting an array, see: [sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort).

### Concatenating
If you start with these arrays:

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with `np.concatenate()`.

In [17]:
# Code here
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

Or, if you start with these arrays:

In [18]:
import numpy as np
x = np.array([[1, 2], [3, 4]])  #(2*2)
y = np.array([[5, 6]])   #shape(1*2)
np.shape(y)

(1, 2)

You can concatenate them with:

In [19]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
#np.concatenate((x, y), axis=1)
y.shape = (2,1)
np.concatenate((x, y), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

**To read more about concatenate, see: [concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate).**

# Section 3: How do you know the shape and size of an array?
This section covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`


- `ndarray.ndim` will tell you the number of `axes`, or `dimensions`, of the array.

- `ndarray.size` will tell you the `total number of elements` of the array. This is the product of the elements of the array’s shape.

- `ndarray.shape` will display a `tuple` of integers that indicate the `number of elements` stored `along each dimension` of the array. If, for example, you have a `2-D` array with `2` rows and `3` columns, the shape of your array is `(2, 3)`.

**For example**, if you create this array:

In [21]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

**Q1  Find the number of dimensions of the array**

In [22]:
# Code here
np.ndim(array_example)
array_example.shape

(3, 2, 4)

**Q2 Find the total number of elements in the array.**

In [23]:
# Code Here
np.size(array_example)

24

In [24]:
# And to find the shape of your array, run:
array_example.shape

(3, 2, 4)

# Sectin 4: Can you reshape an array?
This section covers `arr.reshape()`

**Yes!**

Using `arr.reshape()` will give a new shape to an array without changing the data.

> Just remember that when you use the reshape method, the array you want to produce needs to have the `same number of elements` as the original array.

> If you `start` with an array with `12 elements`, you’ll need to make sure that your `new array` also has a total of `12 elements`.

If you start with this array:

In [25]:
a = np.arange(6)
a
np.shape(a)

(6,)

You can use `reshape()` to reshape your array.

**Try to reshape this array to an array with `three rows` and `two columns`:**

In [26]:
# Code here
b = np.reshape(a, newshape=(3, 2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

**Another Way**

With `np.reshape`, you can specify a few optional parameters:


In [27]:
np.reshape(a, newshape=(2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

**Learn more about shape manipulation [here](https://numpy.org/doc/stable/user/quickstart.html#quickstart-shape-manipulation).**

# Section 5: How to convert a 1D array into a 2D array (how to add a new axis to an array)
This section covers `np.newaxis`, `np.expand_dims`

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. This means that a `1D` array will become a `2D` array, a `2D` array will become a `3D` array, and so on.

**For example**, if you start with this array:

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

You can use `np.newaxis` to add a new axis:

In [29]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [30]:
a2

array([[1, 2, 3, 4, 5, 6]])

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [31]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

Or, for a column vector, you can insert an axis along the second dimension:

In [32]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified `position` with `np.expand_dims`.
- `0` index means row
- `1` index means column

**For example**, if you start with this array:

In [33]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

You can use `np.expand_dims` to add an axis at index `position 1` with:

In [34]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

You can add an axis at index `position 0` with:

In [35]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

**Find more information about [newaxis here](https://numpy.org/doc/stable/reference/arrays.indexing.html#arrays-indexing) and [expand_dims here](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html#numpy.expand_dims).**

# Section 6: Indexing and slicing
You can index and slice NumPy arrays in the same ways you can slice Python lists.

You may want to take a section of your array or specific array elements to use in further analysis or additional operations.
>To do that, you’ll need to `subset`, `slice`, and/or `index` your arrays.

In [36]:
data = np.array([1, 2, 3])

**You can visualize it this way:**
![alt text](S1-pics\slice.png)

In [37]:
data[1]

2

In [38]:
data[0:2]

array([1, 2])

In [39]:
data[1:]

array([2, 3])

In [40]:
data[-2:]

array([2, 3])

If you want to `select values` from your array that fulfill `certain conditions`, it’s straightforward with NumPy.

**For example**, if you start with this array:

In [41]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can easily print all of the values in the array that are `less than 5`.

In [42]:
a[a < 5]

array([1, 2, 3, 4])

**Try this**
- Select all numbers that are `equal` to or `greater` than `5`.

In [43]:
# code here
five_up = a[a >= 5]
five_up

array([ 5,  6,  7,  8,  9, 10, 11, 12])

**Try this**
- Use that condition to index an array.

In [44]:
# code here
inds = np.nonzero(a >= 5)
inds

(array([1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3]))

**Try This**
- Select elements that are `divisible by 2`.

In [45]:
# Code here
divisible_by_2 = a[a%2 == 0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

**Also, you can select elements that satisfy two conditions using the `&` and `|` operators:**

In [46]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

You can also make use of the logical operators `&` and `|` in order to `return boolean values` that specify whether or not the values in an array fulfill a certain condition.

**This can be useful with arrays that contain names or other categorical values.**

In [47]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### You can also use `np.nonzero()` to select elements or indices from an array.

Starting with this array:

In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can use `np.nonzero()` to print the indices of elements that are `less than 5`:

In [49]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In this example, a `tuple` of arrays was returned:
- one for each dimension.
- The `first array` represents the `row indices` where these values are found, and
- the `second array` represents the `column indices` where the values are found.

**You can also use `np.nonzero()` to print the elements in an array that are `less than 5` with:**

In [50]:
print(a[b])

[1 2 3 4]


**What if**

The `element` you’re looking for `doesn’t exist` in the array ?
- then the returned array of indices will be `empty`.

For example:

In [51]:
not_there = np.nonzero(a == 42)
not_there

(array([], dtype=int64), array([], dtype=int64))

**Learn more about [indexing and slicing here](https://numpy.org/doc/stable/user/quickstart.html#quickstart-indexing-slicing-and-iterating) and [here](https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing)**.

**Read more about using the nonzero function at: [nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html#numpy.nonzero)**.



# Section 7: How to create an array from existing data
This section covers `slicing` and `indexing`, `np.vstack()`, `np.hstack()`, `np.hsplit()`, `.view()`, `copy()`

You can easily use create a new array from a section of an existing array.

**Let’s say you have this array:**

In [52]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing
You can create a `new array` from a section of your array any time by specifying where you want to `slice` your array.

**Try To**
- Grabbed a section of your array from index `position 3` through index `position 8`.

In [53]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

### Stack two existing arrays

You can also stack two existing arrays, both `vertically` and `horizontally`.

**Let’s say you have two arrays, `a1` and `a2`:**

In [54]:
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

**Try to stack them `vertically` with `vstack`:**

In [76]:
# Code here
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

**Try to stack them `horizontally` with `hstack`:**

In [77]:
# Code here
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### Split

You can split an array into `several smaller` arrays using `hsplit`. You can specify either the `number of equally shaped` arrays to return `or` the columns after which the `division should occur`.

**Let’s say you have this array:**

In [57]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to `split` this array into `three equally shaped arrays`, you would run:

In [58]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you wanted to split your array after the `third` and `fourth column`, you’d run:

In [59]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

**[Learn more about stacking and splitting arrays here.](https://numpy.org/doc/stable/user/quickstart.html#quickstart-stacking-arrays)**

### Shallow and Deep coping

You can use the `view` method to create a new array object that looks at the same data as the original array (a `shallow copy`).

`Views` are an important NumPy concept!

- NumPy functions, as well as operations like `indexing` and `slicing`, will **`return views`** whenever possible.
- This **saves memory** and is **faster** (no copy of the data has to be made).

> However it’s important to be aware of this - **modifying data in a view also modifies the original array**!

Let’s say you create this array:

In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

**Now we create an array `b1` by slicing a and modify the `first element of b1`.**
>**This will modify the corresponding element in `a` as well!**

In [61]:
# Slice from a (view concept applied - shallow coping)
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [62]:
# modify 1st element of b
b1[0] = 99
b1

array([99,  2,  3,  4])

In [63]:
# lets check what happened with a
# its also modified
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Using the `copy` method will make a complete copy of the array and its data (a `deep copy`). To use this on your array, you could run:

In [64]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
# create a deep copy
b2 = a.copy()
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
# access 1st element of 2d array and modify
b2[1][2] = 77
b2

array([[ 1,  2,  3,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 11, 12]])

In [67]:
# lets check a
# nothing changed in it
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**[Learn more about copies and views here.](https://numpy.org/doc/stable/user/quickstart.html#quickstart-copies-and-views)**

# Section 8: Basic array operations
This section covers `addition`, `subtraction`, `multiplication`, `division`, and more

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “`data`” and one called “`ones`”

![alt_text](S1-pics\arrs1.png)

>You can add the arrays together with the `plus sign`.


**Try It**
- Create two arrays as the following diagrma
- Sum the two arrays

![alt_text](S1-pics\add.png)

In [68]:
# Code here
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

sum_arrs = data + ones
sum_arrs

array([2, 3])

You can, of course, do more than just addition!
![alt_text](S1-pics\many.png)

In [69]:
# Subtraction
data - ones

array([0, 1])

In [70]:
# Multiplication
data * data

array([1, 4])

In [71]:
# Division
data / data

array([1., 1.])

### Sum
Basic operations are simple with NumPy.

If you want to find the `sum of the elements` in an array, you’d use `sum()`.

>This works for `1D arrays`, `2D arrays`, and arrays in `higher dimensions`.

In [72]:
a = np.array([1, 2, 3, 4])
a.sum()

10

To add the `rows` or the `columns` in a `2D array`, you would specify the `axis`.

If you start with this array:

In [73]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [74]:
# You can sum the rows with:
b.sum(axis=0)

array([3, 3])

In [75]:
# You can sum the columns with:
b.sum(axis=1)

array([2, 4])

**[Learn more about basic operations here.](https://numpy.org/doc/stable/user/quickstart.html#quickstart-basic-operations)**

# Thank you for your time and efforts!
### *By:Heba-T-ALLAH Raslan*